// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proxy/socks_uds/config.proto

package socks_uds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_socks_uds_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_socks_uds_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_socks_uds_config_proto_rawDescGZIP(), []int{0}
}

var File_proxy_socks_uds_config_proto protoreflect.FileDescriptor

const file_proxy_socks_uds_config_proto_rawDesc = "" +
	"\n" +
	"\x1cproxy/socks_uds/config.proto\x12\x14xray.proxy.socks_uds\"\x0e\n" +
	"\fServerConfigB\\\n" +
	"\x17Com.Xray.Proxy.SocksUdsP\x01Z)github.com/xtls/xray-core/proxy/socks_uds\xaa\x02\x13Xray.Proxy.SocksUdsb\x06proto3"

var (
	file_proxy_socks_uds_config_proto_rawDescOnce sync.Once
	file_proxy_socks_uds_config_proto_rawDescData []byte
)

func file_proxy_socks_uds_config_proto_rawDescGZIP() []byte {
	file_proxy_socks_uds_config_proto_rawDescOnce.Do(func() {
		file_proxy_socks_uds_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_socks_uds_config_proto_rawDesc), len(file_proxy_socks_uds_config_proto_rawDesc)))
	})
	return file_proxy_socks_uds_config_proto_rawDescData
}

var file_proxy_socks_uds_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_socks_uds_config_proto_goTypes = []any{
	(*ServerConfig)(nil), // 0: xray.proxy.socks_uds.ServerConfig
}
var file_proxy_socks_uds_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_socks_uds_config_proto_init() }
func file_proxy_socks_uds_config_proto_init() {
	if File_proxy_socks_uds_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_socks_uds_config_proto_rawDesc), len(file_proxy_socks_uds_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_socks_uds_config_proto_goTypes,
		DependencyIndexes: file_proxy_socks_uds_config_proto_depIdxs,
		MessageInfos:      file_proxy_socks_uds_config_proto_msgTypes,
	}.Build()
	File_proxy_socks_uds_config_proto = out.File
	file_proxy_socks_uds_config_proto_goTypes = nil
	file_proxy_socks_uds_config_proto_depIdxs = nil
}
